import com.charlatano.settings.*

ACTIVATE_FROM_FIRE_KEY = true
FORCE_AIM_KEY = 5
AIM_FOV = 50
AIM_SPEED_MIN = 28
AIM_SPEED_MAX = 36
AIM_STRICTNESS = 2.4
TARGET_SWAP_MIN_DELAY = 200L
TARGET_SWAP_MAX_DELAY = 350L
PERFECT_AIM = false
PERFECT_AIM_FOV = 4
PERFECT_AIM_CHANCE = 100
AIM_ASSIST_MODE = false
AIM_ASSIST_STRICTNESS = 40
AIM_DURATION = 1
SHIFT_TO_SHOULDER_SHOTS = 4
SHIFT_TO_BODY_SHOTS = 7